DROP TABLE users CASCADE;
DROP TABLE items;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    email varchar(40) NOT NULL UNIQUE,
    name varchar(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    owner_id bigint REFERENCES users(id),
    name varchar(40) NOT NULL,
    description varchar(200) NOT NULL,
    available boolean NOT NULL DEFAULT(false)
);

CREATE TABLE IF NOT EXISTS bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    requester bigint REFERENCES users(id),
    item bigint REFERENCES items(id),
    start_time varchar(40),
    end_time varchar(40),
    status varchar(10)
);
